### PR TITLE
Readme update

### LINKED ISSUE #2: Adding Contribution section to README
Add a contribution section to the README showing how someone can contribute to the project

### PR DESCRIPTION
**Pull request by JVisuri1**
Updated contribution guide

### CODE REVIEW

**Review by itsksquare — CHANGES_REQUESTED** [review]
looks good so far, could you maybe fix the hyperlink in the contents, add one for the contributing section and a line break after every title, also remove the headings "configuring the bot" and "starting the bot for the first time"

**Comment by JVisuri1** [comment]
Updated. Unfortunately i couldn't find those "configuring the bot" and "starting the bot for the first time" titles

**Review by itsksquare — CHANGES_REQUESTED** [review]
ohh I just realized I was looking at the changes the wrong way, apologies, could you maybe do one last change before I merge, remove those line breaks that were just added and fix the hyperlink for "Contributing" in the contents

**Comment by JVisuri1** [comment]
Alright. Hyperlink fixed and <br> tags removed

**Pull request merged**
